### Travis James Smith
February 8th, 2020

HU Extension                  Assignment 01          E89 Deep Learning		                  	
Handed out: 02/01/2020                            Due by 12 noon EST on Saturday, 02/08/2020
 
You are welcome to implement TensorFlow problems in this problem set in any of supported languages. Python is recommended.


In [2]:
import tensorflow as tf

**Problem 1.** In class notes we made a claim that we can implement three essential logical operations: AND, OR and NOT as artificial neurons (perceptors). Write three Python functions which implement the above three operations. As input values you can use integers 1-s and 0-s or Boolean values, True-s and False-s. 
Demonstrate that all three functions return proper logical values (1-s and 0-s or True-s and False-s. 
Please declare all variable and constants using TensofFlow syntax and types. It is a bit of a drag. Just do it.


In [27]:
x_1 = tf.constant([0., 0., 1., 1.])
x_2 = tf.constant([0., 1., 0., 1.])

def AND(t1, t2):
    inputs = -30 + 20 * t1 + 20 * t2
    return tf.round(tf.math.sigmoid(inputs))

def OR(t1, t2):
    inputs = -10 + 20 * t1 + 20 * t2
    return tf.round(tf.math.sigmoid(inputs))

def NOT(t):
    inputs = 10 + -20 * t
    return tf.round(tf.math.sigmoid(inputs))

print("AND: ", AND(x_1, x_2))
print("OR: ", OR(x_1, x_2))
print("NOT: ", NOT(x_1))

AND:  tf.Tensor([0. 0. 0. 1.], shape=(4,), dtype=float32)
OR:  tf.Tensor([0. 1. 1. 1.], shape=(4,), dtype=float32)
NOT:  tf.Tensor([1. 1. 0. 0.], shape=(4,), dtype=float32)


**Problem 2.** Use functions developed in the previous problem to demonstrate that you can implement NOT (x XOR y) logical function. 

In [28]:
# We can model our NOT XOR (XNOR) function as nodes
# in a neural network feeding forward, with two layers
def XNOR(t1, t2):
    node1 = AND(t1, t2)
    node2 = AND(NOT(t1), NOT(t2))
    node3 = OR(node1, node2)
    return tf.round(tf.sigmoid(node3))

print("XNOR: ", XNOR(x_1, x_2))

XNOR:  tf.Tensor([1. 0. 0. 1.], shape=(4,), dtype=float32)


**Problem 3.** Create a TensorFlow Sentence array with three short sentences. Their lengths (in words) should be 3,2, and 4. Transform that sentence array into a Rugged Tensor. Also, transform the rugged tensor into a NumPy array. Print all 

In [77]:
sentence_1 = "A Brown Cow"
sentence_2 = "A Brown"
sentence_3 = "A Brown Cow Jumped"

array = tf.constant([sentence_1, sentence_2, sentence_3])
print("TF Array: ", array)

ragged = tf.strings.split(array)
print("TF Ragged: ", ragged)

numpy = [arr.numpy() for arr in ragged]
print("NP Arrays: ", numpy)

TF Array:  tf.Tensor([b'A Brown Cow' b'A Brown' b'A Brown Cow Jumped'], shape=(3,), dtype=string)
TF Ragged:  <tf.RaggedTensor [[b'A', b'Brown', b'Cow'], [b'A', b'Brown'], [b'A', b'Brown', b'Cow', b'Jumped']]>
NP Array:  [array([b'A', b'Brown', b'Cow'], dtype=object), array([b'A', b'Brown'], dtype=object), array([b'A', b'Brown', b'Cow', b'Jumped'], dtype=object)]


**Problem 4.** Generate a variable as a sparse tensor of outside dimensions 4X4 of DType int8. Populate 5 of its elements with random numbers between 1 and 10 by assigning those values using TensorFlow function(s) to generate random numbers. (You are expected to find those functions in TensorFlow API documentation.) Print dense form of this tensor.



In [102]:
rand = tf.random.uniform(shape=[5,], minval=1, maxval=10, dtype=tf.int64)

# Note that we have to typecast from int64 to int8 for the values, because it looks
# like tf.random.uniform won't generate int8 values
st = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 1], [3, 2], [3, 3]], 
                     values=tf.cast(rand, dtype=tf.int8), dense_shape=[4, 4])

# Print the dense form of the sparse matrix
tf.sparse.to_dense(st)

<tf.Tensor: shape=(4, 4), dtype=int8, numpy=
array([[0, 7, 0, 0],
       [5, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 3, 4]], dtype=int8)>

Solution of this assignment has to be submitted as a single Jupyter notebook (ipynb file), as well as HTML and PDF images of that notebook. To generate those images, use the following command:
  
jupyter nbconvert notebook.ipynb –to html    
jupyter nbconvert notebook.ipynb –to pdf


Please provide meaningful description of actions in all cells of your notebook. Include those descriptions either as Python comments (#) or contents of the adjacent Mardown cells. 
